{
  "openapi": "3.1.0",
  "info": {
    "version": "1.0.0",
    "title": "Contacts API",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "description": "API для роботи з контактами користувача (GoIT HW7).\n"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    },
    {
      "url": "https://nodejs-hw-mongodb-7-8efq.onrender.com"
    }
  ],
  "tags": [
    {
      "name": "Contacts",
      "description": "Операції з контактами"
    }
  ],
  "paths": {
    "/contacts": {
      "get": {
        "tags": [
          "Contacts"
        ],
        "summary": "Отримати список контактів",
        "description": "Повертає список контактів з підтримкою пагінації та сортування.",
        "operationId": "getAllContacts",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "minimum": 1
            },
            "description": "Номер сторінки (пагінація)"
          },
          {
            "in": "query",
            "name": "perPage",
            "schema": {
              "type": "integer",
              "minimum": 1
            },
            "description": "Кількість контактів на сторінку"
          },
          {
            "in": "query",
            "name": "sortBy",
            "schema": {
              "type": "string"
            },
            "description": "Поле для сортування (наприклад, \"name\")"
          },
          {
            "in": "query",
            "name": "sortOrder",
            "schema": {
              "type": "string",
              "enum": [
                "asc",
                "desc"
              ]
            },
            "description": "Порядок сортування 'asc' (за зростанням) або 'desc' (за спаданням)"
          }
        ],
        "responses": {
          "200": {
            "description": "Успішне отримання списку контактів",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "message": {
                      "type": "string",
                      "example": "Successfully found contacts!"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "contacts": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/Contact"
                          }
                        },
                        "page": {
                          "type": "integer",
                          "example": 1
                        },
                        "perPage": {
                          "type": "integer",
                          "example": 2
                        },
                        "totalItems": {
                          "type": "integer",
                          "example": 1
                        },
                        "totalPages": {
                          "type": "integer",
                          "example": 1
                        },
                        "hasPreviousPage": {
                          "type": "boolean",
                          "example": false
                        },
                        "hasNextPage": {
                          "type": "boolean",
                          "example": false
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "summary": "Список контактів з пагінацією",
                    "value": {
                      "status": 200,
                      "message": "Successfully found contacts!",
                      "data": {
                        "contacts": [
                          {
                            "_id": "687113f0d29c1342da1cb9f1",
                            "name": "Hanna",
                            "phoneNumber": "+380000000008",
                            "contactType": "personal",
                            "userId": "6870fa1264fcd7118fa2d80c",
                            "photo": "https://res.cloudinary.com/dica60k30/image/upload/v1752241198/contacts/a0drczlmkphchls0thcc.png",
                            "__v": 0
                          }
                        ],
                        "page": 1,
                        "perPage": 2,
                        "totalItems": 1,
                        "totalPages": 1,
                        "hasPreviousPage": false,
                        "hasNextPage": false
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Некоректний запит",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequest": {
                    "summary": "Некоректний запит",
                    "value": {
                      "status": 400,
                      "message": "Некоректний параметр пагінації",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Неавторизовано",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "Unauthorized": {
                    "summary": "Неавторизовано",
                    "value": {
                      "status": 401,
                      "message": "Authorization header missing or malformed",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Contacts"
        ],
        "summary": "Створити новий контакт",
        "description": "Додає новий контакт для користувача. Дані передаються у форматі multipart/form-data.",
        "operationId": "addContact",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "phoneNumber",
                  "contactType"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Ім'я контакта",
                    "example": "Test Contact"
                  },
                  "email": {
                    "type": "string",
                    "description": "Електронна пошта",
                    "example": "testcontact@example.com"
                  },
                  "phoneNumber": {
                    "type": "string",
                    "description": "Номер телефону",
                    "example": "1234567890"
                  },
                  "contactType": {
                    "type": "string",
                    "description": "Тип контакта (наприклад, \"work\", \"personal\")",
                    "example": "work"
                  },
                  "isFavourite": {
                    "type": "boolean",
                    "description": "Чи обраний контакт улюбленим (опційно)",
                    "example": false
                  },
                  "photo": {
                    "type": "string",
                    "format": "binary",
                    "description": "Фото контакта (опційно)"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Контакт створено",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OneContactResponse"
                },
                "examples": {
                  "Created": {
                    "summary": "Контакт створено",
                    "value": {
                      "status": 201,
                      "message": "Successfully created contact!",
                      "data": {
                        "_id": "687113f0d29c1342da1cb9f1",
                        "name": "Anna",
                        "email": "anna@example.com",
                        "phoneNumber": "+380000000008",
                        "contactType": "personal",
                        "isFavourite": false,
                        "userId": "6870fa1264fcd7118fa2d80c",
                        "photo": "https://res.cloudinary.com/dica60k30/image/upload/v1752241198/contacts/a0drczlmkphchls0thcc.png",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Некоректний запит",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequest": {
                    "summary": "Некоректний запит",
                    "value": {
                      "status": 400,
                      "message": "Validation error",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Неавторизовано",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "Unauthorized": {
                    "summary": "Неавторизовано",
                    "value": {
                      "status": 401,
                      "message": "Authorization header missing or malformed",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts/{contactId}": {
      "get": {
        "tags": [
          "Contacts"
        ],
        "summary": "Отримати контакт за ID",
        "operationId": "getContactById",
        "description": "Повертає контакт по contactId. Потребує авторизації (Bearer Token).",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Унікальний ідентифікатор контакту"
          }
        ],
        "responses": {
          "200": {
            "description": "Контакт знайдено",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OneContactResponse"
                },
                "examples": {
                  "Success": {
                    "summary": "Контакт знайдено",
                    "value": {
                      "status": 200,
                      "message": "Successfully fetched contact!",
                      "data": {
                        "_id": "687113f0d29c1342da1cb9f1",
                        "name": "Anna",
                        "phoneNumber": "+380000000008",
                        "contactType": "personal",
                        "userId": "6870fa1264fcd7118fa2d80c",
                        "photo": "https://res.cloudinary.com/dica60k30/image/upload/v1752241198/contacts/a0drczlmkphchls0thcc.png",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Неавторизовано",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "Unauthorized": {
                    "summary": "Неавторизовано (невірний або прострочений токен)",
                    "value": {
                      "status": 401,
                      "message": "Access token expired",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Контакт не знайдено",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "NotFound": {
                    "summary": "Контакт не знайдено",
                    "value": {
                      "status": 404,
                      "message": "Contact not found",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Contacts"
        ],
        "summary": "Оновити контакт",
        "operationId": "updateContact",
        "description": "Оновлює існуючий контакт за його ID. Можна змінити ім'я, email, номер телефону, тип контакту, isFavourite або фото (усі поля необов'язкові).",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Унікальний ідентифікатор контакту"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Ім'я контакта"
                  },
                  "email": {
                    "type": "string",
                    "description": "Електронна пошта"
                  },
                  "phoneNumber": {
                    "type": "string",
                    "description": "Номер телефону"
                  },
                  "contactType": {
                    "type": "string",
                    "description": "Тип контакта (work/personal/...)"
                  },
                  "isFavourite": {
                    "type": "boolean",
                    "description": "Чи є контакт улюбленим"
                  },
                  "photo": {
                    "type": "string",
                    "format": "binary",
                    "description": "Фото (опціонально)"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Контакт успішно оновлено",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OneContactResponse"
                },
                "examples": {
                  "Success": {
                    "summary": "Контакт оновлено",
                    "value": {
                      "status": 200,
                      "message": "Successfully updated contact!",
                      "data": {
                        "_id": "687113f0d29c1342da1cb9f1",
                        "name": "Anna",
                        "phoneNumber": "+380000000008",
                        "contactType": "personal",
                        "userId": "6870fa1264fcd7118fa2d80c",
                        "photo": "https://res.cloudinary.com/dica60k30/image/upload/v1752241198/contacts/a0drczlmkphchls0thcc.png",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Некоректний запит",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequest": {
                    "summary": "Некоректний запит",
                    "value": {
                      "status": 400,
                      "message": "Invalid contact ID",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Неавторизовано",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "Unauthorized": {
                    "summary": "Неавторизовано",
                    "value": {
                      "status": 401,
                      "message": "Authorization header missing or malformed",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Не знайдено (контакт не існує)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "NotFound": {
                    "summary": "Контакт не знайдено",
                    "value": {
                      "status": 404,
                      "message": "Contact not found",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Contacts"
        ],
        "summary": "Видалити контакт",
        "description": "Видаляє контакт за вказаним ID.",
        "operationId": "deleteContact",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Унікальний ідентифікатор контакту"
          }
        ],
        "responses": {
          "204": {
            "description": "Контакт успішно видалено (No Content)"
          },
          "400": {
            "description": "Некоректний запит",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequest": {
                    "summary": "Некоректний ID",
                    "value": {
                      "status": 400,
                      "message": "Invalid contact ID",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Неавторизовано",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "Unauthorized": {
                    "summary": "Неавторизовано (невірний або прострочений токен)",
                    "value": {
                      "status": 401,
                      "message": "Authorization header missing or malformed",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Не знайдено (контакт не існує)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "NotFound": {
                    "summary": "Контакт не знайдено",
                    "value": {
                      "status": 404,
                      "message": "Contact not found",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "Contact": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "Унікальний ідентифікатор контакту",
            "example": "60d21b4667d0d8992e610c85"
          },
          "name": {
            "type": "string",
            "description": "Ім’я контакту",
            "example": "John Doe"
          },
          "email": {
            "type": "string",
            "description": "Електронна пошта (опціонально)",
            "example": "johndoe@example.com"
          },
          "phoneNumber": {
            "type": "string",
            "description": "Номер телефону",
            "example": 380501234567
          },
          "contactType": {
            "type": "string",
            "description": "Тип контакту (наприклад, work, personal)",
            "example": "work"
          },
          "isFavourite": {
            "type": "boolean",
            "description": "Чи є контакт улюбленим",
            "example": false
          },
          "photo": {
            "type": "string",
            "description": "Фото контакту (URL або порожній рядок)",
            "example": ""
          },
          "userId": {
            "type": "string",
            "description": "Ідентифікатор користувача, якому належить контакт",
            "example": "60d21b4667d0d8992e610c84"
          },
          "__v": {
            "type": "integer",
            "description": "Версія документа (технічне поле)",
            "example": 0
          }
        },
        "required": [
          "_id",
          "name",
          "phoneNumber",
          "contactType",
          "userId"
        ]
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "HTTP-статус відповіді (наприклад, 400, 401, 404, 500)",
            "example": 404
          },
          "message": {
            "type": "string",
            "description": "Опис помилки",
            "example": "Contact not found"
          },
          "data": {
            "description": "null (відсутні дані у випадку помилки)",
            "example": null
          }
        },
        "required": [
          "status",
          "message",
          "data"
        ]
      },
      "OneContactResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "HTTP-статус відповіді (наприклад, 200, 201)",
            "example": 201
          },
          "message": {
            "type": "string",
            "description": "Повідомлення про результат операції",
            "example": "Contact created successfully"
          },
          "data": {
            "$ref": "#/components/schemas/Contact"
          }
        },
        "required": [
          "status",
          "message",
          "data"
        ]
      }
    }
  }
}